repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
        args: ["--line-length", "79" ]
        language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      language_version: python3.9
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910-1'
    hooks:
    -   id: mypy
        verbose: true
        entry: bash -c 'mypy "src/" || true' --
        additional_dependencies: [sqlalchemy==1.4.22,
                                  types-PyYAML,
                                  types-redis,
                                  types-pytz,
                                  types-requests]
