version: "3.9"

services:
  app:
    build: .
    image: fastapi_sandbox:latest
    container_name: fastapi_sandbox
    entrypoint: ["/opt/app/entrypoint.sh"]
    ports:
      - "80:8000"
    env_file: .env
    volumes:
      - ./src/fastapi_sandbox:/opt/app/fastapi_sandbox
      - ./src/alembic:/opt/app/alembic
      - ./src/tests:/opt/app/tests
    restart: on-failure
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/api/readiness" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: postgres:14
#    container_name: ${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./volumes/pgadmin4/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
