version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:8000"
    env_file: .env
    volumes:
      - ./fastapi_sandbox:/app/fastapi_sandbox
      - ./alembic:/app/alembic
      - ./tests:/app/tests
    restart: on-failure
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/api/readiness" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./configs/pgadmin4/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
