apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fastapi-sandbox-r-s
  labels:
    project: education
    app: fastapi_sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi_sandbox
  template:
    metadata:
      name: fastapi-sandbox-pod
      labels:
        project: education
        app: fastapi_sandbox
    spec:
      containers:
        - name: fastapi-sandbox-container
          image: koevgeny10/fastapi_sandbox
          command: [ "/bin/bash" ]
          args: [ "-c", "uvicorn fastapi_sandbox.main:app --host 0.0.0.0 --port 8000" ]
          ports:
            - name: main
              containerPort: 8000
          env:
            - name: DEBUG
              value: "true"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_HOST
              value: "host.minikube.internal"
            - name: POSTGRES_PORT
              value: "5432"
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 80