"""empty message

Revision ID: 42f0676f9812
Revises: d442e7c42359
Create Date: 2022-01-25 22:10:18.247228

"""


# revision identifiers, used by Alembic.
revision = "42f0676f9812"
down_revision = "d442e7c42359"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
