"""empty message

Revision ID: d442e7c42359
Revises: ace7d8939d1c
Create Date: 2022-01-25 21:04:09.763736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d442e7c42359"
down_revision = "ace7d8939d1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Entity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("SomeModel")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SomeModel",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('\"SomeModel_id_seq\"'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("a", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="SomeModel_pkey"),
    )
    op.drop_table("Entity")
    # ### end Alembic commands ###
