"""empty message

Revision ID: ace7d8939d1c
Revises:
Create Date: 2022-01-18 18:30:30.740926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ace7d8939d1c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SomeModel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("a", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("SomeModel")
    # ### end Alembic commands ###
